name: deploytry1

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install &&
           npm -v &&
           echo "BUILDING"  
#            npm run build
           

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           ARGS:  >-  
#             -rltgoDzvO
#             --exclude='.git'
#             --exclude='node_modules/'
#           SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

    - name: Deploying

      run:
         sudo apt install nodejs
         
         sudo apt install npm
         
         npm i -g pm2
         
         mkdir myserver 
         
         git clone https://github.com/data-doll/demo.git myserver 
              
         cd myserver 
         
         npm i
                  
         pm2 start index.js
