name: Slack Notification Demo
on: push
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          SLACK_MESSAGE: 'HELLO DATA DOLL, A PUSH EVENT OCCURED IN YOUR DEMO REPO.'
          SLACK_TITLE: 'Slack Notification Demo'
