name: DemoDeploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install

#     - name: Deploy to Server
# #       uses: easingthemes/ssh-deploy@main
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
# #           ARGS:  >-  
# #             -rltgoDzvO
# #             --exclude='.git'
# #             --exclude='node_modules/'
#           SOURCE: "./"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: ${{ secrets.REMOTE_TARGET }}
#       run:
# #           echo "$SSH_PRIVATE_KEY" > private_key && chmod 400 private_key
# #           ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} '
#             echo "$SSH_PRIVATE_KEY" > private_key && chmod 400 private_key
                        
#             ssh -i private_key ${REMOTE_USER}@${REMOTE_HOST} '
            
#              DIR="/home/ubuntu/server"
             
#              if [ ! -d $DIR ]
#              then
#               mkdir server &&
#               git clone https://github.com/data-doll/demo.git server &&
#               cd server &&
#               npm i
#              else
#               cd server
#              fi
            
#              node index.js
            
#              echo('RUNNING')
           
#            '


    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           ARGS:  >-  
#             -rltgoDzvO
#             --exclude='.git'
#             --exclude='node_modules/'
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          
    - name: Deploying
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           ARGS:  >-  
#             -rltgoDzvO
#             --exclude='.git'
#             --exclude='node_modules/'
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      run:
         sudo apt install nodejs
         
         sudo apt install npm
         
         sudo npm i -g pm2
         
         mkdir myserver &&
         
         git clone https://github.com/data-doll/demo.git myserver &&
              
         cd myserver &&
         
         npm i &&

         pm2 start index.js
            
            
